image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY  # login to gitlab registry
  - export DOCKER_BUILDKIT=1
  - |
    if [[ "$CI_COMMIT_BRANCH" == 'develop' ]]; then
      TAG="dev"
    elif [[ -n "$CI_COMMIT_TAG" ]]; then
      TAG="$CI_COMMIT_TAG"
    else
      TAG="$CI_COMMIT_REF_SLUG"
    fi
    echo "Running on ref '$CI_COMMIT_REF_NAME': TAG = $TAG"

build-dev:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$TAG .
    - docker push $CI_REGISTRY_IMAGE:$TAG
  only:
    - develop
    - tags
